spring.application.name=bigbite-backend

# Native .env file import
spring.config.import=optional:file:.env[.properties]

# Server Port
server.port=${PORT:8080}

# Aiven MySQL Datasource Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-13ba3984-jathushansundararasu-23c8.l.aivencloud.com:16805/defaultdb?sslmode=require}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Settings for Aiven MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
